title: Jean-Marcien C Kablansi
logo: /assets/IMG_7939.jpg
#description: I am a skilled professional with a strong programming background, proficient in Python, SQL, R, MATLAB and VBA. My expertise extends to cloud platforms like Microsoft Azure and data management systems such as Snowflake, making me a valuable asset in data-driven and programming roles.
#show_downloads: true
theme: jekyll-theme-minimal
