title: Jean-Marcien C Kablansi
#logo: /assets/img/heads
description: **Education** Master of Science, Actuarial Science Master of Science, Quantitative Risk Analysis & Management Bachelor of Science, Mathematics
show_downloads: true
theme: jekyll-theme-minimal
