title: Jean-Marcien C Kablansi
logo: /assets/IMG_7939.jpg
description: Master of Science, Actuarial Science n/ Master of Science, Quantitative Risk Analysis & Management Bachelor of Science, Mathematics
show_downloads: true
theme: jekyll-theme-minimal
