title: Jean-Marcien C Kablansi
logo: /assets/IMG_7939.jpg
description: I am a skilled professional with a strong programming background, proficient in Python, SQL, R, MATLAB and VBA. At iptiQ by Swiss Re, I designed and implemented an automated ETL pipeline, developed Python tools for data analysis, and supported pricing and analytics with Python and SQL. Previously, at New York Life Insurance, I used Python and VBA for investment modeling, automation and data integration projects. My expertise extends to cloud platforms like Microsoft Azure and data management systems such as Snowflake, making me a valuable asset in data-driven and programming roles.
show_downloads: true
theme: jekyll-theme-minimal
